package com.jaswanth.auditlog.export.application;

public enum ExportViolation {
    MALFORMED_BUNDLE,
    SIGNATURE_INVALID,
    SEQUENCE_GAP,
    PREVIOUS_HASH_MISMATCH,
    PAYLOAD_PROOF_MISMATCH,
    CONTENT_HASH_MISMATCH,
    RECORD_HASH_MISMATCH,
    CHAIN_HEAD_MISMATCH,
    MATCH_COUNT_MISMATCH,
    SCOPE_MISMATCH,
    UNSUPPORTED_RECORD_KIND
}
