CREATE TABLE audit_event (
    sequence_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    event_type VARCHAR(100) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    resource_type VARCHAR(100) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    payload JSON NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    hash_version SMALLINT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    previous_hash CHAR(64) NOT NULL,
    record_hash CHAR(64) NOT NULL UNIQUE,
    archived_at TIMESTAMP WITH TIME ZONE NULL,
    redacted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_audit_event_actor_sequence
    ON audit_event (actor_id, sequence_number);

CREATE INDEX idx_audit_event_resource_sequence
    ON audit_event (resource_type, resource_id, sequence_number);

CREATE INDEX idx_audit_event_type_sequence
    ON audit_event (event_type, sequence_number);

CREATE INDEX idx_audit_event_occurred_sequence
    ON audit_event (occurred_at, sequence_number);

CREATE TABLE audit_chain_head (
    chain_id SMALLINT PRIMARY KEY,
    last_sequence BIGINT NOT NULL,
    last_hash CHAR(64) NOT NULL,
    lock_version BIGINT NOT NULL
);

INSERT INTO audit_chain_head (chain_id, last_sequence, last_hash, lock_version)
VALUES (1, 0, '0000000000000000000000000000000000000000000000000000000000000000', 0);
